version: "3.8"

services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - proxy
    expose:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx.rule=Host(`gonzalezjoan.com`) || Host(`www.gonzalezjoan.com`)
      - traefik.http.routers.nginx.entrypoints=websecure
      - traefik.http.routers.nginx.tls=true
      - traefik.http.routers.nginx.tls.certresolver=letsencrypt
      - traefik.docker.network=proxy

networks:
  proxy:
    external: true
